### PR TITLE
new EPIK logo for reifork that will distinguish this fork from le bad fedoraware:main

### PR DESCRIPTION
**Pull request by SamlonDev**
please merge this pr so I can feed my family 🙏

### CODE REVIEW

**Comment by SamlonDev** [comment]
logo made by cl_p100 on discord btw

**Comment by phonkv2** [comment]
Remove this

**Comment by SamlonDev** [comment]
updated the logo again

**Comment by TruthNoDare** [comment]
Is really cool

**Comment by rei-kes** [comment]
what no

**Comment by BindUser** [comment]
Ugly as shit

**Pull request closed without merging**
