### PR TITLE
Code cleanups, feature & logic improvements.

### PR DESCRIPTION
**Pull request by RileyKun**
Cleaned up a majority of the logic in Misc in terms of LocalPlayer checks as most of the checks were redundant and not needed. Bunnyhop was refactored completely (it was a mess... It also had a bad bug where you could not double-jump at all under certain conditions). Improved edge detection logic to support up pitch properly (This does however introduce a bug with the resolver that needs to be fixed, but I am too lazy to do so right now).

There were also changes to the logic in Core. A fail check was added for DirectX so we aren't attempting to still load if our dxlevel is set to an unsupported value. There was also a check for compiler flags to disable the in-menu check if we are compiled in debug mode (less key presses, less tedious things. will never affect actual users unless they compile the hack themselves).

### CODE REVIEW

**Comment by lbydesync** [comment]
this is poopy

**Comment by RileyKun** [comment]
> this is poopy

h8r

**Comment by phonkv2** [comment]
give this man mod

**Comment by turn1pwastaken** [comment]
> give this man mod

yeah what he said

**Comment by ShalomWare** [comment]
GIN6x6jWQAAPbdn

**Comment by phonkv2** [comment]
> ![GIN6x6jWQAAPbdn](https://private-user-images.githubusercontent.com/167394426/323461844-36de39c2-d5f9-4f46-b87e-a1a96851cb51.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTM4NDgsIm5iZiI6MTcxMzQxMzU0OCwicGF0aCI6Ii8xNjczOTQ0MjYvMzIzNDYxODQ0LTM2ZGUzOWMyLWQ1ZjktNGY0Ni1iODdlLWExYTk2ODUxY2I1MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNDEyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGNkZTcxZTQzZjIzODNhMDcxNmE4YzhmOGM3YTIwZjQ0N2Y5N2YwZWQ4NzYzMTAxZDVjMjJhZjVhOTdmYTQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jU8Wzu2op0RVKffIpBxX5djwEAP71NPxDLzMjdiVu3Y

nigger

**Comment by ShalomWare** [comment]
> nigger
qu06e4iv0e871

**Comment by ShalomWare** [comment]
@phonkv2

https://github.com/rei-kes/Fedoraware/assets/167394426/f886bc9b-7760-40b5-99e7-79c8eb0de4e8

**Comment by phonkv2** [comment]
> @phonkv2
> 
>  SaveInsta.App.-.3164492622269315828_51663790319.mp4

im gonna touch u

**Comment by ShalomWare** [comment]
> > @phonkv2
> > SaveInsta.App.-.3164492622269315828_51663790319.mp4
> 
> im gonna touch u


https://github.com/rei-kes/Fedoraware/assets/167394426/19cdd18e-5142-433a-a644-7968a6a24214

**Comment by phonkv2** [comment]
> > > @phonkv2
> > > SaveInsta.App.-.3164492622269315828_51663790319.mp4
> > 
> > 
> > im gonna touch u
> 
>  video0-1-2.mp4

????

**Comment by ShalomWare** [comment]
image

**Comment by ShalomWare** [comment]
https://github.com/rei-kes/Fedoraware/assets/167394426/e442ec95-b5f2-4125-ad6c-b2598f9a705c

**Comment by rei-kes** [comment]
I included the majority of this in the latest commit, with some changes to misc & antiaim

**Pull request closed without merging**
